---
title: "OpenHDF5"
author: "Robert Paul"
date: "June 20, 2016"
output: html_document
---

## About this code!

```{r setup-load-libraries}
# load libraries
library(raster)
library(rhdf5)
library(rgdal)

```

## Open a file!

```{r select-file}
# Store the data file path
f <- "../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"
# view h5 structure
h5ls(f)
```

## Import spatial information!

```{r import-spatial-info}
# import spatial information
mapInfo <- h5read(file = f,
                  name = "map info",
                  read.attributes = TRUE)
```

## Let's grab reflectance metadata

```{r get-reflectance-metadata}
# Read in reflectance data attributes
reflInfo <- h5readAttributes(file = f,
                             name = "Reflectance")

# Define the scale factor here
scaleFactor <- reflInfo$'Scale Factor'
# Define No Data value
noDataVal <- as.numeric(reflInfo$'data ignore value')
```

## Import the dimensions of the reflectance data

```{r import-dims}
# open the file for viewing
fid <- H5Fopen(f)
# open the reflectance dataset
did <- H5Dopen(fid,
               "Reflectance")

# Grab the dimensions of the object
sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size

# The data seem to come in rotated; wavelength is 3rd dimension,
# colums are 1st dimension, then rows.

# close everything
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)
```

## View Wavelength Information

```{r view-wavelength}
# Import the center wavelength in um of each band
wavelengths <- h5read(file = f,
                      name = "wavelength")
str(wavelengths)
```

## Read Reflectance Data

```{r read-reflectance}
# Slice data for band 56 from the HDF5 file
b56 <- h5read(file = f,
              name = "Reflectance",
              index = list(1:dims[1], 1:dims[2], 56))
# Note the data are in an array
class(b56)
```

## Convert to matrix!

```{r convert-to-matrix}
# Convert from array to raster
b56 <- b56[,,1]
# plot the data
image(b56)
# Kinda looks funny huh? Force a stretch
image(log(b56),
      main="Band 56 log transformed")

# view distribution, force to non-scientific notation
options("scipen"=100, "digits"=4)

hist(x = b56,
     col = "springgreen",
     main = "Distribution of Reflectance Values\nBand 56")
```

## Data Clean-up

```{r clean-up}
# set No Data value to NA
b56[b56 == noDataVal] <- NA

# Divide all values in b56 by scale factor to get a range of reflectance values
# between 0-1
b56 <- b56/scaleFactor

hist(x = b56,
     col = "springgreen",
     main = "Distribution with No Data value considered\ndata scaled")
```

## A case of flipped data?

```{r flip-raster}
# Transpose row and column
b56 <- t(b56)
image(log(b56), main="Band 56\nTransposed Values")
```

## Define spatial extent

```{r define-extent}
# We can extract the upper left-hand corner coordinates
# Position 4 & 5 are the upper-left corner (x, y) respectively
mapInfo <- unlist(strsplit(mapInfo, ','))
# grab the upper left corner coordinate, cast as numeric
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])

# We can get the x and y resolution too
res <- c(mapInfo[2], mapInfo[3])
res <- as.numeric(res)

# finally calculate the xMax value and the yMin value from the dimensions
# we grabbed above. The xMax is the left corner + number of columns* resolution.
xMax <- xMin + (dims[1]*res[1])
yMin <- yMax - (dims[2]*res[2])

# Also note that x and y are the same (1 m)

# Define raster extent (left, right, top, bottom)
rasExt <- extent(xMin, xMax, yMin, yMax)

# Build the raster with the extent defined
b56r <- raster(b56,
              crs=CRS("+init=epsg:32611"))
# assign CRS
extent(b56r) <- rasExt

plot(b56r,
     main="Raster for Lower Teakettle \nBand 56")
```

## Export to GeoTIFF

```{r export-geotiff}
writeRaster(b56r,
            file = "Outputs/TEAK/band56.tif",
            format = "GTiff",
            naFlag=-9999)
```

## Import NEON Functions

```{r import-using-functions}
library(devtools)
#install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)
epsg <- 32611
# Get band 55
b55 <- open_band(fileName = f,
                 bandNum = 55,
                 epsg = epsg)
# plot data
plot(b55)

# import several bands
bands <- c(58, 34, 19)

# create raster stack
RGBStack <- create_stack(file = f,
                         bands = bands,
                         epsg = epsg)
# Plot it!
plotRGB(RGBStack,
        stretch='lin')

# import several bands
bands <- c(90, 34, 19)

# create color infrared raster stack
CIRStack <- create_stack(file = f,
                         bands = bands,
                         epsg = epsg)

plotRGB(CIRStack,
        stretch='lin')
```

